### ISSUE TITLE
SSL error on installing dependencies

### ISSUE THREAD

**Issue by warriorsoul15** [shibdib/EVE-Discord-Bot#40]
I got composer installed then went into the bot directory and ran composer install and it kicked back an error I couldn't get around.  The earlier SSL errors I could bypass by using -K in curl to get the downloads.

Ideas?

![image](https://cloud.githubusercontent.com/assets/11276980/14113525/6a7b474a-f5a1-11e5-8acf-e93ee8c6ec7c.png)

**Comment by shibdib** [comment]
Seems to be an openSSL issue with certain version of PHP

Best answer I could find is http://stackoverflow.com/a/27254240
