### ISSUE TITLE
run.php errors

### ISSUE THREAD

**Issue by drkthunder02** [shibdib/EVE-Discord-Bot#48]
Getting an uncaught fatal exception when trying to run run.php that deals with the PDOExceptions stating SQLSTATE[HY000]: General error: 1 no such table: storage' in /var/www/discordbot/library/DB.php:45

Basically the stack trace goes out to Db.php, permCache.php.  Any ideas how to get the install to run correctly?

**Comment by shibdib** [comment]
Hmm that's a new one, delete your database folder and try running it again, should force it to reinstall the databases

**Comment by sn0opy** [comment]
Same problem for me

**Comment by shibdib** [comment]
I'm in the process of hosting the DB myself, fuzzworks wasn't a fan of the constant pings the bot does to check for updates. I'll be releasing a fix for this soon.

**Comment by shibdib** [comment]
Do a pull for the latest version, it will then download the latest release from my own servers
