### ISSUE TITLE
run.php initial setup errors

### ISSUE THREAD

**Issue by warriorsoul15** [shibdib/EVE-Discord-Bot#52]
When I do the run.php script it is crapping out.

X-Powered-By: PHP/5.5.34
Content-type: text/html

2016-04-29T09:54:13-05:00 INFO (6): Performing Initial DB Install
2016-04-29T09:54:14-05:00 NOTICE (5): Updating CCP SQLite DB
2016-04-29T09:54:14-05:00 NOTICE (5): Downloading bz2 file and writing it to /home/xxxxx/EVE-Discord-B
ot/library/../database/ccpData.sqlite.bz2
2016-04-29T09:57:07-05:00 NOTICE (5): Opening bz2 file
<br />
<b>Fatal error</b>:  Call to undefined function bzopen() in <b>/home/xxxxx/EVE-Discord-Bot/library/upd
ateCCPData.php</b> on line <b>22</b><br />

**Comment by warriorsoul15** [comment]
I got past that one...  now the Twisted module is crapping out on SQLITE

Building wheels for collected packages: pysqlite, eveapi, beautifulsoup
  Running setup.py bdist_wheel for pysqlite ... error
  Complete output from command /usr/local/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tj4TiP/pysqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpjsp3Cvpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pysqlite2
  copying lib/dump.py -> build/lib.linux-x86_64-2.7/pysqlite2
  copying lib/dbapi2.py -> build/lib.linux-x86_64-2.7/pysqlite2
  copying lib/__init__.py -> build/lib.linux-x86_64-2.7/pysqlite2
  creating build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/transactions.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/dbapi.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/regression.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/dump.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/hooks.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/__init__.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/factory.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/userfunctions.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  copying lib/test/types.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
  running build_ext
  building 'pysqlite2._sqlite' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -IPackage -Isqlite3 -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath. -IPerhaps -Iyou -Ishould -Iadd -Ithe -Idirectory -Icontaining -I`sqlite3.pc' -Ito -Ithe -IPKG_CONFIG_PATH -Ienvironment -Ivariable -INo -Ipackage -I'sqlite3' -Ifound -I/usr/local/miniconda/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
  In file included from src/module.c:24:
  src/connection.h:33:21: error: sqlite3.h: No such file or directory
  In file included from src/module.c:24:
  src/connection.h:38: error: expected specifier-qualifier-list before ‘sqlite3’
  In file included from src/module.c:25:
  src/statement.h:37: error: expected specifier-qualifier-list before ‘sqlite3’
  src/module.c: In function ‘module_connect’:
  src/module.c:63: error: ‘SQLITE_OPEN_READWRITE’ undeclared (first use in this function)
  src/module.c:63: error: (Each undeclared identifier is reported only once
  src/module.c:63: error: for each function it appears in.)
  src/module.c:63: error: ‘SQLITE_OPEN_CREATE’ undeclared (first use in this function)
  src/module.c: In function ‘module_complete’:
  src/module.c:102: warning: implicit declaration of function ‘sqlite3_complete’
  src/module.c: In function ‘init_sqlite’:
  src/module.c:401: warning: implicit declaration of function ‘sqlite3_libversion’
  src/module.c:401: warning: passing argument 1 of ‘PyString_FromString’ makes pointer from integer without a cast
  /usr/local/miniconda/include/python2.7/stringobject.h:63: note: expected ‘const char *’ but argument is of type ‘int’
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pysqlite
  Running setup.py clean for pysqlite
  Running setup.py bdist_wheel for eveapi ... done
  Stored in directory: /home/menfi/.cache/pip/wheels/6d/42/c4/8951ac73fbf76ac74774957480ccc8026b9f992b47a30ac269
  Running setup.py bdist_wheel for beautifulsoup ... done
  Stored in directory: /home/menfi/.cache/pip/wheels/5e/be/6d/ed01d5d434a821557b674c9da976f60b1b93d9009447eb9d16
Successfully built eveapi beautifulsoup
Failed to build pysqlite
Installing collected packages: pysqlite, eveapi, beautifulsoup
  Running setup.py install for pysqlite ... error
    Complete output from command /usr/local/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tj4TiP/pysqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rpELzz-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pysqlite2
    copying lib/dump.py -> build/lib.linux-x86_64-2.7/pysqlite2
    copying lib/dbapi2.py -> build/lib.linux-x86_64-2.7/pysqlite2
    copying lib/__init__.py -> build/lib.linux-x86_64-2.7/pysqlite2
    creating build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/transactions.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/dbapi.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/regression.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/dump.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/hooks.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/__init__.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/factory.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/userfunctions.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/types.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    running build_ext
    building 'pysqlite2._sqlite' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -IPackage -Isqlite3 -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath. -IPerhaps -Iyou -Ishould -Iadd -Ithe -Idirectory -Icontaining -I`sqlite3.pc' -Ito -Ithe -IPKG_CONFIG_PATH -Ienvironment -Ivariable -INo -Ipackage -I'sqlite3' -Ifound -I/usr/local/miniconda/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
    In file included from src/module.c:24:
    src/connection.h:33:21: error: sqlite3.h: No such file or directory
    In file included from src/module.c:24:
    src/connection.h:38: error: expected specifier-qualifier-list before ‘sqlite3’
    In file included from src/module.c:25:
    src/statement.h:37: error: expected specifier-qualifier-list before ‘sqlite3’
    src/module.c: In function ‘module_connect’:
    src/module.c:63: error: ‘SQLITE_OPEN_READWRITE’ undeclared (first use in this function)
    src/module.c:63: error: (Each undeclared identifier is reported only once
    src/module.c:63: error: for each function it appears in.)
    src/module.c:63: error: ‘SQLITE_OPEN_CREATE’ undeclared (first use in this function)
    src/module.c: In function ‘module_complete’:
    src/module.c:102: warning: implicit declaration of function ‘sqlite3_complete’
    src/module.c: In function ‘init_sqlite’:
    src/module.c:401: warning: implicit declaration of function ‘sqlite3_libversion’
    src/module.c:401: warning: passing argument 1 of ‘PyString_FromString’ makes pointer from integer without a cast
    /usr/local/miniconda/include/python2.7/stringobject.h:63: note: expected ‘const char *’ but argument is of type ‘int’
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tj4TiP/pysqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rpELzz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tj4TiP/pysqlite/

**Comment by warriorsoul15** [comment]
you need pysqlite-devel installed   and for that matter pygments for python

**Comment by shibdib** [comment]
The above and also db issues should be fixed with the latest pull
