### ISSUE TITLE
Error on initialization

### ISSUE THREAD

**Issue by Minarch** [shibdib/EVE-Discord-Bot#54]
> root@pi:~/EVE-Discord-Bot# php run.php
> string(49) "SQLSTATE[HY000] [14] unable to open database file"
> 2016-05-21T04:07:26+02:00 INFO (6): Performing Initial DB Install
> 2016-05-21T04:07:26+02:00 WARN (4): Creating users in sluggard.sqlite, since it does not exist
> 2016-05-21T04:07:26+02:00 WARN (4): Creating usersSeen in sluggard.sqlite, since it does not exist
> 2016-05-21T04:07:26+02:00 WARN (4): Creating storage in sluggard.sqlite, since it does not exist
> 2016-05-21T04:07:27+02:00 WARN (4): Creating shipFits in sluggard.sqlite, since it does not exist
> 2016-05-21T04:07:27+02:00 NOTICE (5): Updating CCP SQLite DB
> 2016-05-21T04:07:27+02:00 NOTICE (5): Opening bz2 file
> PHP Warning:  bzopen(/root/EVE-Discord-Bot/library/../database/sqlite-latest.sqlite.bz2): failed to open stream: No such file or directory in /root/EVE-Discord-Bot/library/updateCCPData.php on line 10
> 2016-05-21T04:07:27+02:00 NOTICE (5): Reading from bz2 file
> PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /root/EVE-Discord-Bot/library/updateCCPData.php on line 14
> PHP Warning:  bzread() expects parameter 1 to be resource, boolean given in /root/EVE-Discord-Bot/library/updateCCPData.php on line 15

**Comment by shibdib** [comment]
Ya this will be fixed, I'm in the middle of switching some strain off fuzzworks servers

**Comment by shibdib** [comment]
Should be fixed, update to the latest version
