### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by jpbrowning** [shibdib/EVE-Discord-Bot#57]
Change of corporation tax notification error:

"typeID 19 is an unmapped notification, send Mr Twinkie this whole message via evemail or github issue. corpID: 98459314 newTaxRate: 0.0 oldTaxRate: 50.0"

![tpupctb](https://cloud.githubusercontent.com/assets/5718420/15995549/0ebc76e2-30eb-11e6-95a1-d6789ed814a4.png)

**Comment by shibdib** [comment]
fixed in latest commit
